### ISSUE TITLE
Psychopy HID Error

### ISSUE THREAD

**Issue by 104H** [104H/dyadicdecisionmaking#39]
Code doesn't run, the error is the following on Ubuntu 20.04 and Ubuntu 16:

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
pygame 2.0.0.dev6 (SDL 2.0.10, python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
PsychHID-WARNING: Seems like the libX11 library was *not* initialized for thread-safe mode,
PsychHID-WARNING: because the application host process omitted a required call to
PsychHID-WARNING: XInitThreads() during its startup, as required for safe operation!
PsychHID-WARNING: Unfortunately the application host process already used XLib for
PsychHID-WARNING: something, e.g., for starting up its GUI, so i can not safely work
PsychHID-WARNING: around this problem! Use of multi-threading in PsychHID() might cause
PsychHID-WARNING: malfunctions or even a hard application crash!
PsychHID-WARNING: Please fix the application to call XInitThreads() *before* calling
PsychHID-WARNING: any other libX11 X-Lib functions, or not to call X-Lib at all before using this module.
PsychHID-WARNING: You could force me to call XInitThreads() by setting the environment
PsychHID-WARNING: variable PSYCH_XINITTHREADS to any non-empty value as a workaround, if
PsychHID-WARNING: you like living on the edge, at your own risk though!
PsychHID-WARNING: I will continue, but may malfunction or crash at some point!
PsychHID-INFO: If you are using PsychoPy, simply upgrade to version 3.1.3 or later.
PsychHID-INFO: Otherwise, you can generally fix Python scripts/apps by adding the following
PsychHID-INFO: snippet early enough at the beginning of script execution under X11:
PsychHID-INFO: import ctypes
PsychHID-INFO: xlib = ctypes.cdll.LoadLibrary("libX11.so")
PsychHID-INFO: xlib.XInitThreads()

Error in function KbQueueCreate: 	Incorrect argument type supplied
	Discrepancy between a specified and supplied argument:
		Specified Argument Description:
			direction: Input
			position: 6
			presence:
			formats allowed:
				unclassified
			minimum M: 1
			maximum M: 1
			minimum N: 1
			maximum N: 1
			minimum P: 1
			maximum P: 1
		Provided Argument Description:
			direction: Input
			position: 6
			presence: present
			format: int64
			number of dimensions: 0
				 M: 1
				 N: 1
				 P: 1
PsychHID:KbQueueCreate: Usage:

PsychHID('KbQueueCreate', [deviceNumber][, keyFlags=all][, numValuators=0][, numSlots=10000][, flags=0][, windowHandle=0])
Traceback (most recent call last):
  File "experiment_files/dyadic.py", line 175, in <module>
    kb = keyboard.Keyboard()
  File "/usr/lib/python3/dist-packages/psychopy/hardware/keyboard.py", line 166, in __init__
    buffer = _keyBuffers.getBuffer(devId, bufferSize)
  File "/usr/lib/python3/dist-packages/psychopy/hardware/keyboard.py", line 306, in getBuffer
    self[kb_id] = _KeyBuffer(bufferSize=bufferSize,
  File "/usr/lib/python3/dist-packages/psychopy/hardware/keyboard.py", line 348, in __init__
    self.dev = hid.Keyboard(kb_id)  # a PTB keyboard object
  File "/home/hunaid/.local/lib/python3.8/site-packages/psychtoolbox/hid.py", line 137, in __init__
    self._create_queue(buffer_size)
  File "/home/hunaid/.local/lib/python3.8/site-packages/psychtoolbox/hid.py", line 144, in _create_queue
    PsychHID('KbQueueCreate', self.device_number,
TypeError: Incorrect argument type supplied
1.1323 	WARNING 	Monitor specification not found. Creating a temporary one...
4.1910 	WARNING 	Couldn't measure a consistent frame rate.
  - Is your graphics card set to sync to vertical blank?
  - Are you running other processes on your computer?

4.2241 	WARNING 	Pyglet text does not honor the Window setting `blendMode='add'` so 'avg' will be used for the text (but objects drawn after can be added)
4.3990 	WARNING 	Pyglet text does not honor the Window setting `blendMode='add'` so 'avg' will be used for the text (but objects drawn after can be added)
4.4017 	WARNING 	Pyglet text does not honor the Window setting `blendMode='add'` so 'avg' will be used for the text (but objects drawn after can be added)
4.4255 	WARNING 	Pyglet text does not honor the Window setting `blendMode='add'` so 'avg' will be used for the text (but objects drawn after can be added)
4.4275 	WARNING 	Pyglet text does not honor the Window setting `blendMode='add'` so 'avg' will be used for the text (but objects drawn after can be added)
4.4294 	WARNING 	Pyglet text does not honor the Window setting `blendMode='add'` so 'avg' will be used for the text (but objects drawn after can be added)
```

**Comment by 104H** [comment]
The solution is to downgrade to `psychtoolbox version 3.0.17.7` or earlier.
